version: "3"

services:
  pyrin_explorer:
    container_name: pyrin_explorer
    image: supertypo/pyrin-explorer:latest
    restart: unless-stopped
    environment:
      API_URI: "http://localhost:8000"
      API_WS_URI: "ws://localhost:8000"
    ports:
      - "8080:8080/tcp"

  pyrin_rest_server:
    container_name: pyrin_rest_server
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    restart: unless-stopped
    command: pipenv run uvicorn main:app --reload --host 0.0.0.0 --port 8000 
    volumes:
      - "../:/app"
    environment:
      PYIPAD_HOST_1: pyrin:13110
      SQL_URI: postgresql+asyncpg://postgres:postgres@postgresql:5432/postgres
    ports:
      - "8000:8000/tcp"
    links:
      - pyrin
      - postgresql

  pyrin_db_filler:
    container_name: pyrin_db_filler
    image: supertypo/pyrin-db-filler:latest
    restart: unless-stopped
    environment:
      DEBUG: "true"
      PYIPAD_HOST_1: pyrin:13110
      SQL_URI: postgresql://postgres:postgres@postgresql:5432/postgres
    links:
      - pyrin
      - postgresql

  postgresql:
    container_name: postgresql
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432/tcp"
    volumes:
      - postgresql:/var/lib/postgresql/data/

  pyrin:
    container_name: pyrin
    image: supertypo/pyrin:latest
    restart: unless-stopped
    ports:
      - "13110:13110/tcp"
      - "13111:13111/tcp"
    volumes:
      - pyrin:/app/data/
    command: pyrin --utxoindex --connect=kdxweb.pyrincalc.net

volumes:
  postgresql:
  pyrin:
